# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 192)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.players_number_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.players_number_spinBox.setGeometry(QtCore.QRect(158, 7, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.players_number_spinBox.setFont(font)
        self.players_number_spinBox.setReadOnly(False)
        self.players_number_spinBox.setMinimum(1)
        self.players_number_spinBox.setMaximum(4)
        self.players_number_spinBox.setObjectName("players_number_spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 111, 16))
        self.label.setObjectName("label")
        self.player1_name = QtWidgets.QLineEdit(self.centralwidget)
        self.player1_name.setGeometry(QtCore.QRect(120, 50, 113, 20))
        self.player1_name.setObjectName("player1_name")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(30, 50, 81, 20))
        self.label_1.setObjectName("label_1")
        self.player2_name = QtWidgets.QLineEdit(self.centralwidget)
        self.player2_name.setEnabled(False)
        self.player2_name.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.player2_name.setObjectName("player2_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 81, 20))
        self.label_2.setObjectName("label_2")
        self.player3_name = QtWidgets.QLineEdit(self.centralwidget)
        self.player3_name.setEnabled(False)
        self.player3_name.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.player3_name.setObjectName("player3_name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 20))
        self.label_3.setObjectName("label_3")
        self.player4_name = QtWidgets.QLineEdit(self.centralwidget)
        self.player4_name.setEnabled(False)
        self.player4_name.setGeometry(QtCore.QRect(120, 140, 113, 20))
        self.player4_name.setObjectName("player4_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(296, 10, 131, 20))
        self.label_5.setObjectName("label_5")
        self.folderName_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.folderName_Edit.setGeometry(QtCore.QRect(290, 50, 113, 20))
        self.folderName_Edit.setObjectName("folderName_Edit")
        self.open_folder_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_folder_Btn.setGeometry(QtCore.QRect(410, 46, 25, 25))
        self.open_folder_Btn.setObjectName("open_folder_Btn")
        self.start_game_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_game_Btn.setGeometry(QtCore.QRect(280, 120, 151, 41))
        self.start_game_Btn.setObjectName("start_game_Btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memorino"))
        self.label.setText(_translate("MainWindow", "Количество игроков"))
        self.player1_name.setText(_translate("MainWindow", "Игрок 1"))
        self.label_1.setText(_translate("MainWindow", "Имя игрока 1"))
        self.player2_name.setText(_translate("MainWindow", "Игрок 2"))
        self.label_2.setText(_translate("MainWindow", "Имя игрока 2"))
        self.player3_name.setText(_translate("MainWindow", "Игрок 3"))
        self.label_3.setText(_translate("MainWindow", "Имя игрока 3"))
        self.player4_name.setText(_translate("MainWindow", "Игрок 4"))
        self.label_4.setText(_translate("MainWindow", "Имя игрока 4"))
        self.label_5.setText(_translate("MainWindow", "Папка с карточками"))
        self.folderName_Edit.setText(_translate("MainWindow", "data"))
        self.open_folder_Btn.setText(_translate("MainWindow", "..."))
        self.start_game_Btn.setText(_translate("MainWindow", "ИГРАТЬ"))
